# Generated by Django 5.2.4 on 2025-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_client_name_remove_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Client_name',
            field=models.CharField(default='Unknown Client', max_length=100),
        ),
    ]
