# Generated by Django 5.2.4 on 2025-07-29 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_memberassigned_created_at_memberassigned_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
