# Generated by Django 5.2.4 on 2025-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectactivity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberassigned',
            name='assigned_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberassigned',
            name='assigned_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hosting_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('dead', 'Dead')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('completed', 'Completed'), ('on-hold', 'On Hold')], max_length=20, null=True),
        ),
    ]
