# Generated by Django 5.2.4 on 2025-08-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_memberassigned_assigned_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('hot', 'Hot'), ('inactive', 'Inactive'), ('dead', 'Dead')], max_length=50, null=True),
        ),
    ]
