# Generated by Django 5.2.4 on 2025-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hot', 'Hot'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
