# Generated by Django 5.2.4 on 2025-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('past', 'Past')], default='current', max_length=20),
        ),
    ]
