# Generated by Django 5.2.4 on 2025-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hot', 'Hot')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('hot', 'Hot'), ('dead', 'Dead')], max_length=50, null=True),
        ),
    ]
