# Generated by Django 5.2.4 on 2025-08-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('current', 'Currently Working'), ('past', 'Ex Employee')], default='current', max_length=20),
        ),
    ]
