# Generated by Django 5.2.4 on 2025-08-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
